#lang ivy1.7

attribute method = mc

type bv8
interpret bv8 -> bv[8] #lowering this lowers execution time

object spec = {

var s1 : bv8
var s2 : bv8
var s3 : bv8
var s4 : bv8
var s5 : bv8
var s6 : bv8

var r1 : bv8
var r2 : bv8
var r3 : bv8
var r4 : bv8
var r5 : bv8
var r6 : bv8

var q1 : bv8
var q2 : bv8
var q3 : bv8
var q4 : bv8
var q5 : bv8
var q6 : bv8

var p1 : bv8
var p2 : bv8
var p3 : bv8
var p4 : bv8
var p5 : bv8
var p6 : bv8

var o1 : bv8
var o2 : bv8
var o3 : bv8
var o4 : bv8
var o5 : bv8
var o6 : bv8

var n1 : bv8
var n2 : bv8
var n3 : bv8
var n4 : bv8
var n5 : bv8
var n6 : bv8

var m1 : bv8
var m2 : bv8
var m3 : bv8
var m4 : bv8
var m5 : bv8
var m6 : bv8

var l1 : bv8
var l2 : bv8
var l3 : bv8
var l4 : bv8
var l5 : bv8
var l6 : bv8

after init {
  s1 := 1;
  s2 := 50;
  s3 := 0;
  s4 := 1;
  s5 := 50;
  s6 := 0;
  
  r1 := 0;
  r2 := 0;
  r3 := 0;
  r4 := 0;
  r5 := 0;
  r6 := 0;
  
  q1 := 0;
  q2 := 0;
  q3 := 0;
  q4 := 0;
  q5 := 0;
  q6 := 0;

  p1 := 0;
  p2 := 0;
  p3 := 0;
  p4 := 0;
  p5 := 0;
  p6 := 0;

  o1 := 0;
  o2 := 0;
  o3 := 0;
  o4 := 0;
  o5 := 0;
  o6 := 0;

  n1 := 0;
  n2 := 0;
  n3 := 0;
  n4 := 0;
  n5 := 0;
  n6 := 0;

  m1 := 0;
  m2 := 0;
  m3 := 0;
  m4 := 0;
  m5 := 0;
  m6 := 0;

  l1 := 0;
  l2 := 0;
  l3 := 0;
  l4 := 0;
  l5 := 0;
  l6 := 0;
  
} #init

action snake = {
  l1 := m1;
  l2 := m2;
  l3 := m3;
  l4 := m4;
  l5 := m5;
  l6 := m6;
  
  m1 := n1;
  m2 := n2;
  m3 := n3;
  m4 := n4;
  m5 := n5;
  m6 := n6;
  
  n1 := o1;
  n2 := o2;
  n3 := o3;
  n4 := o4;
  n5 := o5;
  n6 := o6;

  o1 := p1;
  o2 := p2;
  o3 := p3;
  o4 := p4;
  o5 := p5;
  o6 := p6;

  p1 := q1;
  p2 := q2;
  p3 := q3;
  p4 := q4;
  p5 := q5;
  p6 := q6;

  q1 := r1;
  q2 := r2;
  q3 := r3;
  q4 := r4;
  q5 := r5;
  q6 := r6;

  r1 := s1;
  r2 := s2;
  r3 := s3;
  r4 := s4;
  r5 := s5;
  r6 := s6;
}

action r_one = {
  if (s1 > 0 & s1 ~= 0) & (s2 > 0 & s2 ~= 0) & s5 ~= 40 {
    call snake;
    s1 := s1 - 1;
    s2 := s2 - 1;
    s3 := s3 + 1;
  };
} #end r_one

action r_two = {
  if (s3 > 0 & s3 ~= 0) & s5 ~= 40 {
    call snake;
    s1 := s1 + 1;
    s2 := s2 + 1;
    s3 := s3 - 1;
  };
} #end r_two

action r_three = {
  if (s3 > 0 & s3 ~= 0) & s5 ~= 40 {
    call snake;
    s1 := s1 + 1;
    s3 := s3 - 1;
    s5 := s5 + 1;
  };
} #end r_three

action r_four = {
  if (s4 > 0 & s4 ~= 0) & (s5 > 0 & s5 ~= 0) & s5 ~= 40 {
    call snake;
    s4 := s4 - 1;
    s5 := s5 - 1;
    s6 := s6 + 1;
  };
} #end r_four

action r_five = {
  if (s6 > 0 & s6 ~= 0) & s5 ~= 40 {
    call snake;
    s4 := s4 + 1;
    s5 := s5 + 1;
    s6 := s6 - 1;
  };
} #end r_five

action r_six = {
  if (s6 > 0 & s6 ~= 0) & s5 ~= 40 {
    call snake;
    s4 := s4 + 1;
    s2 := s2 + 1;
    s6 := s6 - 1;
  };
} #end r_six

export r_one
export r_two
export r_three
export r_four
export r_five
export r_six

} #end spec

invariant (spec.s5 ~= 40)