# Validate all metadata

name: Validate Metadata

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check:
  
    # For debugging. Only run from "spec" branch for now
    if: github.head_ref == 'spec'
  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      #- name: Install dependencies
      #  run: |
      #    python -m pip install --upgrade pip
      #    if [ -f Scripts/requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run metadata validation script
        run: ./Scripts/manager.py validate
